{'type': 'text', 'text': {'content': 'docker ps', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker ps', 'href': None}
{'type': 'text', 'text': {'content': 'docker compose bulid', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker compose bulid', 'href': None}
{'type': 'text', 'text': {'content': 'docker compose up -d →起動（バックグ ラウンド）', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker compose up -d →起動（バックグラウンド）', 'href': None}
{'type': 'text', 'text': {'content': 'or', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'or', 'href': None}
{'type': 'text', 'text': {'content': 'docker compose up --build ⇒ buildとupを同時にする', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker compose up --build ⇒ buildとupを同時にする', 'href': None}
{'type': 'text', 'text': {'content': 'docker compose down → 終了', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker compose down → 終了', 'href': None}
{'type': 'text', 'text': {'content': 'docker compose logs web →ログ見る', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker compose logs web →ログ見る', 'href': None}
{'type': 'text', 'text': {'content': 'docker compose restert web', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker compose restert web', 'href': None}
{'type': 'text', 'text': {'content': '改行', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '改行', 'href': None}
{'type': 'text', 'text': {'content': 'docker compose up してから↓', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker compose up してから↓', 'href': None}
{'type': 'text', 'text': {'content': 'docker compose exec 言語名 bash', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'docker compose exec 言語名 bash', 'href': None}
{'type': 'text', 'text': {'content': '言語名にはservicesの下のやつ打つ', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '言語名にはservicesの下のやつ打つ', 'href': None}
{'type': 'text', 'text': {'content': '改行', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '改行', 'href': None}
{'type': 'text', 'text': {'content': 'dockeerfile →一つのコンテナの設計図（イメージを作成）', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'dockeerfile →一つのコンテナの設計図（イメージを 作成）', 'href': None}
{'type': 'text', 'text': {'content': 'compose.yml →複数コンテナの管理', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'compose.yml →複数コンテナの管理', 'href': None}
{'type': 'text', 'text': {'content': '改行', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '改行', 'href': None}
{'type': 'text', 'text': {'content': 'dockerfile ', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'dockerfile ', 'href': None}
{'type': 'text', 'text': {'content': 'FROM ⇒ os,言語等の宣言的な  (.latest で最新) これはDocker Hub側から取ってくることが多い', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'FROM ⇒ os,言語等の宣言的な  (.latestで最新) これはDocker Hub側から取ってくることが多い', 'href': None}
{'type': 'text', 'text': {'content': 'WORKDIR ⇒ コンテナの開始位置', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'WORKDIR ⇒ コンテナの開始位置', 'href': None}
{'type': 'text', 'text': {'content': 'COPY ⇒ dockerfileのある位置から相対的なディレクトリにある内容をWORKDIR直下にコピー', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'COPY ⇒ dockerfileのある位置から相対的なディレクトリにある内容をWORKDIR直下にコピー', 'href': None}
{'type': 'text', 'text': {'content': 'RUN ⇒ compose up時のコマンド', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'RUN ⇒ compose up時のコマンド', 'href': None}
{'type': 'text', 'text': {'content': 'CMD ⇒ 言語を起動したときに使用するコ マンド', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'CMD ⇒ 言語を起動したときに使用するコマンド', 'href': None}
{'type': 'text', 'text': {'content': 'ARG ⇒ 変数宣言', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'ARG ⇒ 変数宣言', 'href': None}
{'type': 'text', 'text': {'content': 'USER ⇒ 起動するユーザーを指定', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'USER ⇒ 起動するユーザーを指定', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000↓ユーザー同期のコード', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000↓ユーザー同期のコード', 'href': None}
{'type': 'text', 'text': {'content': '改行', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '改行', 'href': None}
{'type': 'text', 'text': {'content': 'yml', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'yml', 'href': None}
{'type': 'text', 'text': {'content': 'service⇒必ず書く', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': 'service⇒必ず書く', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000その下⇒FROMのやつ', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000その下⇒FROMのやつ', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000build ⇒必ず書く', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000build ⇒必ず書く', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000\u3000以下二つはdockerfileに関する情報', 'link': None}, 'annotations': {'bold': False, 'italic': True, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'red'}, 'plain_text': '\u3000\u3000\u3000\u3000以下二つはdockerfileに関する情報', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000\u3000context ⇒ folder名', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000\u3000context ⇒ folder名', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000\u3000dockerfile ⇒ file名', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000\u3000dockerfile ⇒ file名', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000volumes ', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000volumes ', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000\u3000./py ⇒ ホスト側がデータ保持\u3000ｐｙはディレクトリ名', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000\u3000./py ⇒ ホスト側がデータ保持\u3000ｐｙはディレクトリ名', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000\u3000data ⇒ Docker側がデータ保持', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000\u3000data ⇒ Docker側がデータ保 持', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000ports', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline'}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000init', 'href': None}
}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000init', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000\u3000終了処理の高速化', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000\u3000終了処理の高速 化', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000env_file', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000env_file', 'href': None}
{'type': 'text', 'text': {'content': '\u3000\u3000\u3000\u3000設定ファイル', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '\u3000\u3000\u3000\u3000設定ファイル', 'href': None}
